#!/bin/bash

#SCRIPT FOR LOGS GENERATION

LOG_FOLDER="/var/log/test"
mkdir -p $LOG_FOLDER
echo "$LOG_FOLDER"
ls -ltr /var/log/test/
LOG_SCRIPT=$(echo $0 | awk -F "." '{print $1F}')

LOGS="$LOG_FOLDER/$LOG_SCRIPT.log"

echo $LOG_SCRIPT

ls -ltr &>>$LOGS
ls -12 &>>$LOGS

id -u
