#!/bin/bash

#SCRIPT FOR LOGS GENERATION

LOG_FOLDER="/var/log/test"
mkdir -p $LOG_FOLDER
echo "$LOG_FOLDER"
ls -ltr /var/log/test/
LOG_SCRIPT=$(echo $0 | awk -F "." '{print $1F}')

LOGS=$($LOG_FILE/$LOG_SCRIPT.log)

ls -ltr &>>$LOGS
ls -12 $>>$LOGS

echo id -u
