- name: configuring cart application
  become: yes
  hosts: cart
  tasks: 
  - name: disabling default nodejs
    ansible.builtin.command: dnf module disable nodejs

  - name: enable nodejs 1.24
    ansible.builtin.command: dnf module enable nodejs:20

  - name: nodejs:20 installation
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: creating system user - roboshop
    ansible.builtin.user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      system: true
  
  - name: copy the applcation code
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
     dest: /tmp/cart.zip

  - name: unzip the application code
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes
  
  - name: install nodejs dependencies
    community.general.npm: 
      name: npm
      path: /app
  
  - name: creating cart.service 
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service
  
  - name: Deamon reload
    ansible.builtin.systemd_service:
      dameon_reload: yes

  - name: start and enable cart
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes



  
      