- name: Intalling MySql via ansible
  hosts: mysql
  become: yes
  tasks:
    - name: installing mysql db
      ansible.builtin.dnf:
        name: mysql-server
        state: present

    - name: start mysql db
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true


    - name: change root password
      ansible.builtin.dnf: mysql_secure_installation --set-root-pass RoboShop@1