- name: Intalling MySql via ansible
  hosts: mysql
  become: yes
  tasks:
    - name: MYsql - Installation
      ansible.builtin.dnf:
        name: mysql-server
        state: present

    - name: start mysql db
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true


    - name: Root Password - change
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1