- name: Redis configuration for roboshop
  become: yes
  hosts: redis
  tasks: 
  - name: Redis - defaul redis disabling
    ansible.builtin.command: dnf module disable redis -y

  - name: Redis - eanble version 7
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: Redis - Installing
    ansible.builtin.dnf:
      name: redis
      state: present
  
  - name: Remote connection enabling
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  
  - name: Procted node - disable
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: protected-mode
      line: protected-mode no

  - name: Redis restart & enable
    ansible.builtin.service:
      name: redis
      state: restarted
      enabled: yes