- name: configuring shpping for roboshop application
  hosts: shipping
  become: yes
  tasks:
  - name: installing maven & mysql client
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql

  - name: System User creation
    ansible.builtin.user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      system: true

  - name: Creating /app dir
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Shipping Application code download
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: unzipping the code
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: Install Maven dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: Jar file rename
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app



  # - name: Download Maven dependencies and build Roboshop application
  #   ansible.builtin.command: "{{ item }}"
  #     loop:
  #     - mvn clean package
  #     - mv target/shipping-1.0.jar shipping.jar 
  #   args:
  #     chdir: /app

  - name: Create shipping service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: Daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  - name: Shipping service start and enable
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes

  - name: Load data
    tags:
    - import
    community.mysql.mysql_db:
      name: all
      login_user: root
      login_password: RoboShop@1
      login_host: mysql.singireddy.shop
      state: import
      target: "{{ item }}"
      loop:
      - /app/db/schema.sql
      - /app/db/app-user.sql
      - /app/db/master-data.sql

  - name: Restart Shipping service
    tags:
    - target
    ansible.builtin.service:
      name: shipping
      state: start